<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="/img/apple-icon.png">
    <link rel="icon" type="image/png" href="/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Volley-ball.eu Gestion de scéances.</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    <!-- CSS Files -->
    <link href="/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/css/materialize-test.css" rel="stylesheet"/>
    <link href="/css/material-kit.css" rel="stylesheet"/>

    <link href="/css/demo.css" rel="stylesheet" />

</head>

<body class="index-page">
<!-- Navbar -->
<nav class="navbar navbar-transparent navbar-fixed-top navbar-color-on-scroll">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-index">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/">
                <div class="logo-container">
                    <div class="logo">
                        <img src="/img/logo.png" alt="Creative Tim Logo" rel="tooltip" title="<b>Material Kit</b> was Designed & Coded with care by the staff from <b>Creative Tim</b>" data-placement="bottom" data-html="true">
                    </div>
                    <div class="brand">
                        Volley-ball.eu
                    </div>
                </div>
            </a>
        </div>

        <div class="collapse navbar-collapse" id="navigation-index">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a title="Follow us on Twitter" href="#">
                        <i class="fa fa-twitter"></i> Présentation
                    </a>
                </li>
                <li>
                    <a title="Like us on Facebook" href="#">
                        <i class="fa fa-facebook-square"></i> Utilisation
                    </a>
                </li>
                <li>
                    <a title="Follow us on Instagram" href="#">
                        <i class="fa fa-instagram"></i> Notification
                    </a>
                </li>
                <li>
                    <a title="Se connecter" href="#" data-toggle="modal" data-target="#modale-signin">
                        <i class="material-icons">power_settings_new</i> Connexion
                    </a>
                </li>
                <li>
                    <a title="Créer un compte" href="#" data-toggle="modal" data-target="#modale-signup">
                        <i class="material-icons">account_circle</i> Créer un compte
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- End Navbar -->
<div class="wrapper">
    <?php echo $this->content ?>
    <footer class="footer">
        <div class="container">
            <nav class="pull-left">
                <ul>
                    <li>
                        <a href="http://www.creative-tim.com">
                            Creative Tim
                        </a>
                    </li>
                    <li>
                        <a href="http://presentation.creative-tim.com">
                           About Us
                        </a>
                    </li>
                    <li>
                        <a href="http://blog.creative-tim.com">
                           Blog
                        </a>
                    </li>
                    <li>
                        <a href="http://www.creative-tim.com/license">
                            Licenses
                        </a>
                    </li>
                </ul>
            </nav>
            <div class="copyright pull-right">
                &copy; 2016, made with <i class="material-icons">favorite</i> by Creative Tim for a better web.
            </div>
        </div>
    </footer>
</div>

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large lime">
        <i class="fa fa-pencil"></i>
    </a>

    <ul>
        <li><a class="btn-floating red btn-tooltip" data-toggle="tooltip" data-placement="left" title="Tooltip on left"><i class="fa fa-star"></i></a></li>
        <li><a class="btn-floating yellow darken-1 btn-tooltip" data-toggle="tooltip" data-placement="left" title="Tooltip on left"><i class="fa fa-user"></i></a></li>
        <li><a class="btn-floating green btn-tooltip" data-toggle="tooltip" data-placement="left" title="Tooltip on left"><i class="fa fa-envelope"></i></a></li>
        <li><a class="btn-floating blue btn-tooltip" data-toggle="tooltip" data-placement="left" title="Tooltip on left"><i class="fa fa-shopping-cart"></i></a></li>
    </ul>
</div>

<!-- Sart Signin Modal -->
<div class="modal fade" id="modale-signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="row">
                <div class="card card-signup">
                    <form class="form" method="" action="">
                        <div class="header header-primary text-center">
                            <h4>Créer un compte</h4>
                        </div>
                        <div class="content">

                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">fingerprint</i>
                                </span>
                                <input type="text" class="form-control" placeholder="Nom...">
                            </div>

                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">face</i>
                                </span>
                                <input type="text" class="form-control" placeholder="Prénom...">
                            </div>

                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">email</i>
                                </span>
                                <input type="text" class="form-control" placeholder="Email...">
                            </div>

                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">lock_outline</i>
                                </span>
                                <input type="password" placeholder="Mot de passe..." class="form-control" />
                            </div>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">lock_outline</i>
                                </span>
                                <input type="password" placeholder="Confirmation de Mdp..." class="form-control" />
                            </div>
                        </div>
                        <div class="footer text-center">
                            <a href="#pablo" class="btn btn-simple btn-primary btn-lg">Créer son compte</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Sart login Modal -->
<div class="modal fade" id="modale-signin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="row">
                <div class="card card-signup">
                    <form class="form" method="" action="">
                        <div class="header header-primary text-center">
                            <h4>Se connecter</h4>
                        </div>
                        <div class="content">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">email</i>
                                </span>
                                <input type="text" class="form-control" placeholder="Email...">
                            </div>

                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="material-icons">lock_outline</i>
                                </span>
                                <input type="password" placeholder="Password..." class="form-control" />
                            </div>
                        </div>
                        <div class="footer text-center">
                            <a href="#pablo" class="btn btn-simple btn-primary btn-lg">S'identifier</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!--  End Modal -->
</body>
<!--   Core JS Files   -->
<script src="/js/jquery.min.js" type="text/javascript"></script>
<script src="/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/js/materialize-test.js"></script>
<script src="/js/material.min.js"></script>

<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="/js/nouislider.min.js" type="text/javascript"></script>

<!--  Plugin for the Datepicker, full documentation here: http://www.eyecon.ro/bootstrap-datepicker/ -->
<script src="/js/bootstrap-datepicker.js" type="text/javascript"></script>

<!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
<script src="/js/material-kit.js" type="text/javascript"></script>

<script type="text/javascript">

    $().ready(function(){
        // the body of this function is in /material-kit.js
        materialKit.initSliders();
        window_width = $(window).width();

        if (window_width >= 992){
            big_image = $('.wrapper > .header');

            $(window).on('scroll', materialKitDemo.checkScrollForParallax);
        }

    });
</script>

</html>

